### ISSUE TITLE
Not working in Insider Preview Build 17639 with Sets

### ISSUE THREAD

**Issue by naefl** [sdias/win-10-virtual-desktop-enhancer#106]
Moving windows is not working anymore with the shortcuts since build 17600, which introduced sets, for the skip ahead builds of windows 10. Potentially you ran into trouble with the "Sets" feature? Still working in RS4 Preview builds

**Comment by mzomparelli** [comment]
In 1803 (17134) update that was just released `IApplicatioinView` was changed. Then again in the pre-release 17600 builds up to 17661 the changes are to 1IApplicationView` and `IApplicationViewCollection`

I have these interfaces partially documented and working. I would like help with the unknown procedures.

https://github.com/mzomparelli/zVirtualDesktop/issues/186

Also, there is this request to Microsoft to start documenting the virtual desktop interfaces. It would be helpful if we could all vote that up and get Microsoft to document.

https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/34150927-stabilize-virtual-desktop-api

I've heard of Pin Window issues in 17665, but I'm unable to find a copy of that build to test.

**Comment by mzomparelli** [comment]
I have working interfaces for builds 17134, 17761, and 17666 at the following link. There are unknown procedures so if you guys figure out what they do then please let me know.

The only interfaces that are changing in these builds are `IApplicationView` and `IApplicationViewCollection`. All other interfaces needed for virtual desktops are unchanged at this time.

https://github.com/mzomparelli/zVirtualDesktop/wiki

**Comment by sdias** [comment]
I've published a new release with fixes, let me know if it works for you.
https://github.com/sdias/win-10-virtual-desktop-enhancer/releases/tag/0.11.2

**Comment by charmesal** [comment]
This still doesn't work on build 17713
Updates to latest release and moving a window to another desktop is impossible

**Comment by phpcitizen** [comment]
I'm on 1809 - 17758.1

Tray icon does not change when desktop change. But the shortcut keys seem to work.

**Comment by phpcitizen** [comment]
Patch for icon change problem for latest insider 17758.1

https://github.com/sdias/win-10-virtual-desktop-enhancer/compare/master...phpcitizen:patch-1
